#160522376  Mocha Test View all Orders
Johnpaul-Borree/Fast-Food-Fast pull request #13
Opened 2018-09-14 21:09 UTC by Johnpaul-Borree

#### What does this PR do?
Test api endpoint  GET /api/v1/orders
#### Description of Task to be completed?
- write tests for endpoint
- Ensure all tests pass
- look up continuous integration changes with test
#### How should this be manually tested?
- run command  npm run test
#### What are the relevant pivotal tracker stories?
#160522376 
#### Screenshots (if appropriate)
![screenshot 16](https://user-images.githubusercontent.com/25976032/45575249-c1119800-b86a-11e8-8174-c991e3f70f92.png)

2018-09-15 12:19 UTC, KaiserPhemi requested changes
Work on feedback

2018-09-15 12:19 UTC, KaiserPhemi commented on src/controller/ordersControllers.js
>  export function postOrder (req, res) {
#### Critical
Same feedback on #11

2018-09-15 12:19 UTC, KaiserPhemi commented on test/ordersTests.js
> +});
#### Nitpick
Add a new line

2018-09-15 22:48 UTC, Johnpaul-Borree commented on test/ordersTests.js
> +});
Finished implementing feedback

2018-09-16 17:12 UTC, Johnpaul-Borree commented
merging view all orders mocha test to develop

2018-09-16 17:12 UTC, merged